# Copyright (c) 2024 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../_schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  new_network_services_bgp_vrf_config:
    type: bool
    default: true
    description: |-
      This key was used to generate BGP configuration for network services even when `evpn` is not in the address families for the node as well as the VRF.
      This is now part of the default behavior so this key has been removed.
    deprecation:
      warning: true
      removed: true
      remove_in_version: 5.0.0
      url: https://avd.arista.com/5.x/docs/porting-guides/5.x.x.html#bgp-is-now-configured-for-network-services-vrfs-even-if-evpn-is-not-part-of-the-address-families
